DESTINOS_DOMICILIO = {
    'aguascalientes': ('Aguascalientes', 'Aguascalientes'),
    'calvillo': ('Calvillo', 'Aguascalientes'),
    'jesús maría': ('Jesús María', 'Jalisco'),
    'pabellón de arteaga': ('Pabellón De Arteaga', 'Aguascalientes'),
    'villa hidalgo': ('Villa Hidalgo', 'Aguascalientes'),
    'teocaltiche': ('Teocaltiche', 'Aguascalientes'),
    'rincón de romos': ('Rincón De Romos', 'Aguascalientes'),
    'san francisco de los romo': ('San Francisco De Los Romo', 'Aguascalientes'),
    'ensenada': ('Ensenada', 'Baja California'),
    'mexicali': ('Mexicali', 'Baja California'),
    'san luis río colorado': ('San Luis Río Colorado', 'Sonora'),
    'puerto peñasco': ('Puerto Peñasco', 'Baja California'),
    'vicente guerrero': ('Vicente Guerrero', 'Baja California'),
    'san quintín': ('San Quintín', 'Baja California'),
    'tijuana': ('Tijuana', 'Baja California'),
    'cadereyta de morelos': ('Cadereyta De Morelos', 'Querétaro'),
    'colón': ('Colón', 'Querétaro'),
    'corregidora': ('Corregidora', 'Querétaro'),
    'el marqués': ('El Marqués', 'Querétaro'),
    'ezequiel montes': ('Ezequiel Montes', 'Querétaro'),
    'pedro escobedo': ('Pedro Escobedo', 'Querétaro'),
    'querétaro': ('Querétaro', 'Querétaro'),
    'san juan del río': ('San Juan Del Río', 'Querétaro'),
    'tequisquiapan': ('Tequisquiapan', 'Querétaro'),
    'cárdenas': ('Cárdenas', 'Tabasco'),
    'comalcalco': ('Comalcalco', 'Tabasco'),
    'cunduacán': ('Cunduacán', 'Tabasco'),
    'huimanguillo': ('Huimanguillo', 'Tabasco'),
    'jalapa': ('Jalapa', 'Tabasco'),
    'jalapa de méndez': ('Jalapa De Méndez', 'Tabasco'),
    'macuspana': ('Macuspana', 'Tabasco'),
    'nacajuca': ('Nacajuca', 'Tabasco'),
    'paraíso': ('Paraíso', 'Tabasco'),
    'teapa': ('Teapa', 'Tabasco'),
    'villahermosa': ('Villahermosa', 'Tabasco'),
    'la paz': ('La Paz', 'Edo Mex'),
    'loreto': ('Loreto', 'Baja California Sur'),
    'los cabos': ('Los Cabos', 'Baja California Sur'),
    'heroica mulegé': ('Heroica Mulegé', 'Baja California Sur'),
    'campeche': ('Campeche', 'Campeche'),
    'cd del carmen': ('Cd Del Carmen', 'Campeche'),
    'arriaga': ('Arriaga', 'Chiapas'),
    'berriozábal': ('Berriozábal', 'Chiapas'),
    'chiapas de corzo': ('Chiapas De Corzo', 'Chiapas'),
    'cintalapa': ('Cintalapa', 'Chiapas'),
    'comitán de domínguez': ('Comitán De Domínguez', 'Chiapas'),
    'palenque': ('Palenque', 'Chiapas'),
    'pijijiapan': ('Pijijiapan', 'Chiapas'),
    'san cristóbal de las casas': ('San Cristóbal De Las Casas', 'Chiapas'),
    'suchiapa': ('Suchiapa', 'Chiapas'),
    'tapachula': ('Tapachula', 'Chiapas'),
    'tonalá': ('Tonalá', 'Jalisco'),
    'tuxtla gutiérrez': ('Tuxtla Gutiérrez', 'Chiapas'),
    'altamira': ('Altamira', 'Tamaulipas'),
    'cd madero': ('Cd Madero', 'Tamaulipas'),
    'cd victoria': ('Cd Victoria', 'Tamaulipas'),
    'matamoros': ('Matamoros', 'Coahuila'),
    'miguel alemán': ('Miguel Alemán', 'Tamaulipas'),
    'nuevo laredo': ('Nuevo Laredo', 'Tamaulipas'),
    'reynosa': ('Reynosa', 'Tamaulipas'),
    'río bravo': ('Río Bravo', 'Tamaulipas'),
    'tampico': ('Tampico', 'Tamaulipas'),
    'allende': ('Allende', 'Nuevo León'),
    'apodaca': ('Apodaca', 'Nuevo León'),
    'acadereita jiménez': ('Acadereita Jiménez', 'Nuevo León'),
    'garcía': ('García', 'Nuevo León'),
    'gral escobedo': ('Gral Escobedo', 'Nuevo León'),
    'guadalupe': ('Guadalupe', 'Nuevo León'),
    'san pedro garza garcía': ('San Pedro Garza García', 'Nuevo León'),
    'sta catarina': ('Sta Catarina', 'Nuevo León'),
    'juárez': ('Juárez', 'Nuevo León'),
    'linares': ('Linares', 'Nuevo León'),
    'montemorelos': ('Montemorelos', 'Nuevo León'),
    'monterrey': ('Monterrey', 'Nuevo León'),
    'san nicolás de los garza': ('San Nicolás De Los Garza', 'Nuevo León'),
    'santiago': ('Santiago', 'Nuevo León'),
    'camargo': ('Camargo', 'Chihuahua'),
    'cd cuauhtémoc': ('Cd Cuauhtémoc', 'Chihuahua'),
    'cd juárez': ('Cd Juárez', 'Chihuahua'),
    'chihuahua': ('Chihuahua', 'Chihuahua'),
    'delicias': ('Delicias', 'Chihuahua'),
    'hidalgo del parral': ('Hidalgo Del Parral', 'Chihuahua'),
    'jiménez': ('Jiménez', 'Chihuahua'),
    'álvaro obregón': ('Álvaro Obregón', 'Ciudad de México'),
    'atzcapozalco': ('Atzcapozalco', 'Ciudad de México'),
    'benito juárez': ('Benito Juárez', 'Ciudad de México'),
    'coyoacán': ('Coyoacán', 'Ciudad de México'),
    'cuajimalpa de morelos': ('Cuajimalpa De Morelos', 'Ciudad de México'),
    'iztapalapa': ('Iztapalapa', 'Ciudad de México'),
    'magdalena contreras': ('Magdalena Contreras', 'Ciudad de México'),
    'miguel hidalgo': ('Miguel Hidalgo', 'Ciudad de México'),
    'milpa alta': ('Milpa Alta', 'Ciudad de México'),
    'tláhuac': ('Tláhuac', 'Ciudad de México'),
    'tlalpan': ('Tlalpan', 'Ciudad de México'),
    'venustiano carranza': ('Venustiano Carranza', 'Ciudad de México'),
    'xochimilco': ('Xochimilco', 'Ciudad de México'),
    'culiacán': ('Culiacán', 'Sinaloa'),
    'el rosario': ('El Rosario', 'Sinaloa'),
    'elota': ('Elota', 'Sinaloa'),
    'escuinapa': ('Escuinapa', 'Sinaloa'),
    'guasave': ('Guasave', 'Sinaloa'),
    'los mochis': ('Los Mochis', 'Sinaloa'),
    'mazatlán': ('Mazatlán', 'Sinaloa'),
    'navolato': ('Navolato', 'Sinaloa'),
    'salvador alvarado': ('Salvador Alvarado', 'Sinaloa'),
    'acuña': ('Acuña', 'Coahuila'),
    'arteaga': ('Arteaga', 'Coahuila'),
    'castaños': ('Castaños', 'Coahuila'),
    'francisco i madero': ('Francisco I Madero', 'Coahuila'),
    'frontera': ('Frontera', 'Coahuila'),
    'monclova': ('Monclova', 'Coahuila'),
    'nava': ('Nava', 'Coahuila'),
    'piedras negras': ('Piedras Negras', 'Coahuila'),
    'ramos arizpe': ('Ramos Arizpe', 'Coahuila'),
    'saltillo': ('Saltillo', 'Coahuila'),
    'torreón': ('Torreón', 'Coahuila'),
    'villa de álvarez': ('Villa De Álvarez', 'Colima'),
    'durango': ('Durango', 'Durango'),
    'gómez palacio': ('Gómez Palacio', 'Durango'),
    'lerdo': ('Lerdo', 'Durango'),
    'pueblo nuevo': ('Pueblo Nuevo', 'Durango'),
    'santiago papasquiaro': ('Santiago Papasquiaro', 'Durango'),
    'titlan de antonio car': ('Titlan De Antonio Car', 'Tlaxcala'),
    'apizaco': ('Apizaco', 'Tlaxcala'),
    'chiautempan': ('Chiautempan', 'Tlaxcala'),
    'huamantla': ('Huamantla', 'Tlaxcala'),
    'panotla': ('Panotla', 'Tlaxcala'),
    'tepeyanco': ('Tepeyanco', 'Tlaxcala'),
    'tetla de la solidaridad': ('Tetla De La Solidaridad', 'Tlaxcala'),
    'tlaxcala': ('Tlaxcala', 'Tlaxcala'),
    'tlaxco': ('Tlaxco', 'Tlaxcala'),
    'totolac': ('Totolac', 'Tlaxcala'),
    'xaloztoc': ('Xaloztoc', 'Tlaxcala'),
    'xicohtzinco': ('Xicohtzinco', 'Tlaxcala'),
    'zacatelco': ('Zacatelco', 'Tlaxcala'),
    'atenco': ('Atenco', 'Edo Mex'),
    'atizapán de zaragoza': ('Atizapán De Zaragoza', 'Edo Mex'),
    'atlacomulco': ('Atlacomulco', 'Edo Mex'),
    'chalco': ('Chalco', 'Edo Mex'),
    'chicoloapan': ('Chicoloapan', 'Edo Mex'),
    'chiconcuan': ('Chiconcuan', 'Edo Mex'),
    'chimalhuacán': ('Chimalhuacán', 'Edo Mex'),
    'coacalco': ('Coacalco', 'Edo Mex'),
    'coyotepec': ('Coyotepec', 'Edo Mex'),
    'cuautitlán izcalli': ('Cuautitlán Izcalli', 'Edo Mex'),
    'ecatepec': ('Ecatepec', 'Edo Mex'),
    'huehuetoca': ('Huehuetoca', 'Edo Mex'),
    'huixquilucan': ('Huixquilucan', 'Edo Mex'),
    'jilotepec': ('Jilotepec', 'Edo Mex'),
    'melchor ocampo': ('Melchor Ocampo', 'Edo Mex'),
    'metepec': ('Metepec', 'Edo Mex'),
    'naucalpan de juárez': ('Naucalpan De Juárez', 'Edo Mex'),
    'nezahualcóyotl': ('Nezahualcóyotl', 'Edo Mex'),
    'nicolás romero': ('Nicolás Romero', 'Edo Mex'),
    'ocoyoacac': ('Ocoyoacac', 'Edo Mex'),
    'palotitlán': ('Palotitlán', 'Edo Mex'),
    'oyaniquilpan de juárez': ('Oyaniquilpan De Juárez', 'Edo Mex'),
    'temac': ('Temac', 'Edo Mex'),
    'teoloyucan': ('Teoloyucan', 'Edo Mex'),
    'tepotzotlán': ('Tepotzotlán', 'Edo Mex'),
    'tepetlaoxtoc': ('Tepetlaoxtoc', 'Edo Mex'),
    'texcoco': ('Texcoco', 'Edo Mex'),
    'tlalnepantla': ('Tlalnepantla', 'Edo Mex'),
    'toluca': ('Toluca', 'Edo Mex'),
    'tonatico': ('Tonatico', 'Edo Mex'),
    'tultepec': ('Tultepec', 'Edo Mex'),
    'tultitlán': ('Tultitlán', 'Edo Mex'),
    'ciudad fernández': ('Ciudad Fernández', 'San Luis Potosí'),
    'ciudad valles': ('Ciudad Valles', 'San Luis Potosí'),
    'matehuala': ('Matehuala', 'San Luis Potosí'),
    'río verde': ('Río Verde', 'San Luis Potosí'),
    'san luis potosí': ('San Luis Potosí', 'San Luis Potosí'),
    'soledad de graciano sánchez': ('Soledad De Graciano Sánchez', 'San Luis Potosí'),
    'cancún': ('Cancún', 'Quintana Roo'),
    'cozumel': ('Cozumel', 'Quintana Roo'),
    'chetumal': ('Chetumal', 'Quintana Roo'),
    'playa del carmen': ('Playa Del Carmen', 'Quintana Roo'),
    'puerto morelos': ('Puerto Morelos', 'Quintana Roo'),
    'abasolo': ('Abasolo', 'Guanajuato'),
    'celaya': ('Celaya', 'Guanajuato'),
    'cortazar': ('Cortazar', 'Guanajuato'),
    'dolores hidalgo': ('Dolores Hidalgo', 'Guanajuato'),
    'guanajuato': ('Guanajuato', 'Guanajuato'),
    'irapuato': ('Irapuato', 'Guanajuato'),
    'león': ('León', 'Guanajuato'),
    'moroleón': ('Moroleón', 'Guanajuato'),
    'pénjamo': ('Pénjamo', 'Guanajuato'),
    'purísima del rincón': ('Purísima Del Rincón', 'Guanajuato'),
    'romita': ('Romita', 'Guanajuato'),
    'salvatierra': ('Salvatierra', 'Guanajuato'),
    'san francisco del rincón': ('San Francisco Del Rincón', 'Guanajuato'),
    'san josé iturbide': ('San José Iturbide', 'Guanajuato'),
    'san luis de la paz': ('San Luis De La Paz', 'Guanajuato'),
    'san miguel de allende': ('San Miguel De Allende', 'Guanajuato'),
    'silao': ('Silao', 'Guanajuato'),
    'uriangato': ('Uriangato', 'Guanajuato'),
    'arandas': ('Arandas', 'Jalisco'),
    'atotonilco el alto': ('Atotonilco El Alto', 'Jalisco'),
    'autlán de navarro': ('Autlán De Navarro', 'Jalisco'),
    'chapala': ('Chapala', 'Jalisco'),
    'cocula': ('Cocula', 'Jalisco'),
    'salto': ('Salto', 'Jalisco'),
    'guadalajara': ('Guadalajara', 'Jalisco'),
    'jalostitlán': ('Jalostitlán', 'Jalisco'),
    'jocotepec': ('Jocotepec', 'Jalisco'),
    'la barca': ('La Barca', 'Jalisco'),
    'lagos de moreno': ('Lagos De Moreno', 'Jalisco'),
    'magdalena': ('Magdalena', 'Sonora'),
    'tlaquepaque': ('Tlaquepaque', 'Jalisco'),
    'zapopan': ('Zapopan', 'Jalisco'),
    'zapotlán el grande': ('Zapotlán El Grande', 'Jalisco'),
    'zapotlanejo': ('Zapotlanejo', 'Jalisco'),
    'ocotlán': ('Ocotlán', 'Jalisco'),
    'puerto vallarta': ('Puerto Vallarta', 'Jalisco'),
    'san juan de los lagos': ('San Juan De Los Lagos', 'Jalisco'),
    'san miguel el alto': ('San Miguel El Alto', 'Jalisco'),
    'tala': ('Tala', 'Jalisco'),
    'tlajomulco de zúñiga': ('Tlajomulco De Zúñiga', 'Jalisco'),
    'acapulco de juárez': ('Acapulco De Juárez', 'Guerrero'),
    'chilpancingo de los bravo': ('Chilpancingo De Los Bravo', 'Guerrero'),
    'iguala de la independencia': ('Iguala De La Independencia', 'Guerrero'),
    'taxco de alarcón': ('Taxco De Alarcón', 'Guerrero'),
    'zihuatanejo (ixtapa)': ('Zihuatanejo (Ixtapa)', 'Guerrero'),
    'acaponeta': ('Acaponeta', 'Nayarit'),
    'bahía de banderas': ('Bahía De Banderas', 'Nayarit'),
    'compostela': ('Compostela', 'Nayarit'),
    'rosa morada': ('Rosa Morada', 'Nayarit'),
    'ruiz': ('Ruiz', 'Nayarit'),
    'santiago ixcuintla': ('Santiago Ixcuintla', 'Nayarit'),
    'santa maría del oro': ('Santa María Del Oro', 'Nayarit'),
    'tecuala': ('Tecuala', 'Nayarit'),
    'tepic': ('Tepic', 'Nayarit'),
    'tuxpan': ('Tuxpan', 'Nayarit'),
    'xalisco': ('Xalisco', 'Nayarit'),
    'actopan': ('Actopan', 'Hidalgo'),
    'apan': ('Apan', 'Hidalgo'),
    'atitalaquia': ('Atitalaquia', 'Hidalgo'),
    'atotonilco el grande': ('Atotonilco El Grande', 'Hidalgo'),
    'cuautepec de hinojosa': ('Cuautepec De Hinojosa', 'Hidalgo'),
    'huichapan': ('Huichapan', 'Hidalgo'),
    'ixmiquilpan': ('Ixmiquilpan', 'Hidalgo'),
    'mineral de la reforma': ('Mineral De La Reforma', 'Hidalgo'),
    'mixquiahuala de juárez': ('Mixquiahuala De Juárez', 'Hidalgo'),
    'pachuca de soto': ('Pachuca De Soto', 'Hidalgo'),
    'santiago tulantepec de lugo': ('Santiago Tulantepec De Lugo', 'Hidalgo'),
    'guerrero': ('Guerrero', 'Hidalgo'),
    'tepeapulco': ('Tepeapulco', 'Hidalgo'),
    'tepeji del río ocampo': ('Tepeji Del Río Ocampo', 'Hidalgo'),
    'tizayuca': ('Tizayuca', 'Hidalgo'),
    'tlahuelilpan': ('Tlahuelilpan', 'Hidalgo'),
    'tula de allende': ('Tula De Allende', 'Hidalgo'),
    'tulancingo de bravo': ('Tulancingo De Bravo', 'Hidalgo'),
    'juitepec': ('Juitepec', 'Hidalgo'),
    'yautepec': ('Yautepec', 'Hidalgo'),
    'apatzingán de la construcción': ('Apatzingán De La Construcción', 'Michoacán'),
    'cd hidalgo': ('Cd Hidalgo', 'Michoacán'),
    'jacona': ('Jacona', 'Michoacán'),
    'jiquilpan': ('Jiquilpan', 'Michoacán'),
    'la piedad de cabadas': ('La Piedad De Cabadas', 'Michoacán'),
    'lázaro cárdenas': ('Lázaro Cárdenas', 'Michoacán'),
    'maravatío de ocampo': ('Maravatío De Ocampo', 'Michoacán'),
    'morelia': ('Morelia', 'Michoacán'),
    'pátzcuaro': ('Pátzcuaro', 'Michoacán'),
    'purépero ichais': ('Purépero Ichais', 'Michoacán'),
    'quiroga': ('Quiroga', 'Michoacán'),
    'sahuayo de morelos': ('Sahuayo De Morelos', 'Michoacán'),
    'tarímbaro': ('Tarímbaro', 'Michoacán'),
    'uruapan': ('Uruapan', 'Michoacán'),
    'zacapu': ('Zacapu', 'Michoacán'),
    'zamora de hidalgo': ('Zamora De Hidalgo', 'Michoacán'),
    'acajete': ('Acajete', 'Puebla'),
    'acatlán': ('Acatlán', 'Puebla'),
    'acatzingo': ('Acatzingo', 'Puebla'),
    'amozoc': ('Amozoc', 'Puebla'),
    'atilizco': ('Atilizco', 'Puebla'),
    'chignahuapan': ('Chignahuapan', 'Puebla'),
    'chinautla': ('Chinautla', 'Puebla'),
    'coapiaxcla de madero': ('Coapiaxcla De Madero', 'Puebla'),
    'cuautlancingo': ('Cuautlancingo', 'Puebla'),
    'izúcar de matamoros': ('Izúcar De Matamoros', 'Puebla'),
    'libres': ('Libres', 'Puebla'),
    'puebla': ('Puebla', 'Puebla'),
    'quecholac': ('Quecholac', 'Puebla'),
    'san jose chiapa': ('San Jose Chiapa', 'Puebla'),
    'san martín texmelucan': ('San Martín Texmelucan', 'Puebla'),
    'san pedro cholula': ('San Pedro Cholula', 'Puebla'),
    'san salvador huixcolotla': ('San Salvador Huixcolotla', 'Puebla'),
    'san salvador huixcolotia': ('San Salvador Huixcolotia', 'Puebla'),
    'tehuacán': ('Tehuacán', 'Puebla'),
    'tepeaca': ('Tepeaca', 'Puebla'),
    'teziutlán': ('Teziutlán', 'Puebla'),
    'tecamachalco': ('Tecamachalco', 'Puebla'),
    'zicotepec': ('Zicotepec', 'Puebla'),
    'zacatlán': ('Zacatlán', 'Puebla'),
    'agua prieta': ('Agua Prieta', 'Sonora'),
    'caborca': ('Caborca', 'Sonora'),
    'cd obregón': ('Cd Obregón', 'Sonora'),
    'cananea': ('Cananea', 'Sonora'),
    'etchojoa': ('Etchojoa', 'Sonora'),
    'guaymas': ('Guaymas', 'Sonora'),
    'hermosillo': ('Hermosillo', 'Sonora'),
    'huatabampo': ('Huatabampo', 'Sonora'),
    'imuris': ('Imuris', 'Sonora'),
    'navojoa': ('Navojoa', 'Sonora'),
    'nogales': ('Nogales', 'Sonora'),
    'pto peñasco': ('Pto Peñasco', 'Sonora'),
    'sta ana': ('Sta Ana', 'Sonora'),
    'asunción nochixtlán': ('Asunción Nochixtlán', 'Oaxaca'),
    'huajuapan de león': ('Huajuapan De León', 'Oaxaca'),
    'oaxaca de juárez': ('Oaxaca De Juárez', 'Oaxaca'),
    'san agustín de las juntas': ('San Agustín De Las Juntas', 'Oaxaca'),
    'san agustín etla': ('San Agustín Etla', 'Oaxaca'),
    'san andrés huayápam': ('San Andrés Huayápam', 'Oaxaca'),
    'san antonio de la cal': ('San Antonio De La Cal', 'Oaxaca'),
    'san jacinto amilpas': ('San Jacinto Amilpas', 'Oaxaca'),
    'san juan bautista tuxtepec': ('San Juan Bautista Tuxtepec', 'Oaxaca'),
    'san lorenzo cacaotepec': ('San Lorenzo Cacaotepec', 'Oaxaca'),
    'san pablo etla': ('San Pablo Etla', 'Oaxaca'),
    'san sebastián tutla': ('San Sebastián Tutla', 'Oaxaca'),
    'santa cruz amilpas': ('Santa Cruz Amilpas', 'Oaxaca'),
    'santa cruz xoxocotlán': ('Santa Cruz Xoxocotlán', 'Oaxaca'),
    'santa lucía del camino': ('Santa Lucía Del Camino', 'Oaxaca'),
    'santa maría del tule': ('Santa María Del Tule', 'Oaxaca'),
    'santiago matatlán': ('Santiago Matatlán', 'Oaxaca'),
    'tlalixtla': ('Tlalixtla', 'Oaxaca'),
    'villa de etla': ('Villa De Etla', 'Oaxaca'),
}

DESTINOS_OCURRE = {
    'aguascalientes': ('Aguascalientes', 'Aguascalientes'),
    'ensenada': ('Ensenada', 'Baja California'),
    'mexicali': ('Mexicali', 'Baja California'),
    'tijuana': ('Tijuana', 'Baja California'),
    'la paz': ('La Paz', 'Baja California Sur'),
    'los cabos': ('Los Cabos', 'Baja California Sur'),
    'campeche': ('Campeche', 'Campeche'),
    'atlacomulco': ('Atlacomulco', 'Ciudad de México'),
    'av. central': ('Av. Central', 'Ciudad de México'),
    'av.revolucion': ('Av.Revolucion', 'Ciudad de México'),
    'cuautitlán': ('Cuautitlán', 'Ciudad de México'),
    'ecatepec 2': ('Ecatepec 2', 'Ciudad de México'),
    'gustavo baz': ('Gustavo Baz', 'Ciudad de México'),
    'huehuehuetoca': ('Huehuehuetoca', 'Ciudad de México'),
    'iztacalco': ('Iztacalco', 'Ciudad de México'),
    'ignacio zaragoza': ('Ignacio Zaragoza', 'Ciudad de México'),
    'marina nacional': ('Marina Nacional', 'Ciudad de México'),
    'naucalpan': ('Naucalpan', 'Ciudad de México'),
    'tepotzotlán': ('Tepotzotlán', 'Ciudad de México'),
    'texcoco': ('Texcoco', 'Ciudad de México'),
    'tlalnepantla': ('Tlalnepantla', 'Ciudad de México'),
    'toluca': ('Toluca', 'Ciudad de México'),
    'tultitlán': ('Tultitlán', 'Ciudad de México'),
    'vallejo': ('Vallejo', 'Ciudad de México'),
    'vallejo 2': ('Vallejo 2', 'Ciudad de México'),
    'san cristóbal de las casas': ('San Cristóbal De Las Casas', 'Chiapas'),
    'tapachula': ('Tapachula', 'Chiapas'),
    'tuxtla gtz': ('Tuxtla Gtz', 'Chiapas'),
    'cd juárez': ('Cd Juárez', 'Chihuahua'),
    'chihuahua': ('Chihuahua', 'Chihuahua'),
    'ramos arizpe': ('Ramos Arizpe', 'Coahuila'),
    'saltillo': ('Saltillo', 'Coahuila'),
    'torreón': ('Torreón', 'Coahuila'),
    'colima': ('Colima', 'Colima'),
    'manzanillo': ('Manzanillo', 'Colima'),
    'durango': ('Durango', 'Durango'),
    'gómez palacio': ('Gómez Palacio', 'Durango'),
    'celaya': ('Celaya', 'Guanajuato'),
    'dolores hidalgo': ('Dolores Hidalgo', 'Guanajuato'),
    'irapuato': ('Irapuato', 'Guanajuato'),
    'león aeropuerto': ('León Aeropuerto', 'Guanajuato'),
    'león central camionera': ('León Central Camionera', 'Guanajuato'),
    'moroleón': ('Moroleón', 'Guanajuato'),
    'purísima del rincón': ('Purísima Del Rincón', 'Guanajuato'),
    'san miguel de allende': ('San Miguel De Allende', 'Guanajuato'),
    'acapulco': ('Acapulco', 'Guerrero'),
    'pachuca': ('Pachuca', 'Hidalgo'),
    'arandas': ('Arandas', 'Jalisco'),
    'guadalajara': ('Guadalajara', 'Jalisco'),
    'lagos de moreno': ('Lagos De Moreno', 'Jalisco'),
    'ocotlán': ('Ocotlán', 'Jalisco'),
    'puerto vallarta': ('Puerto Vallarta', 'Jalisco'),
    'san juan de los lagos': ('San Juan De Los Lagos', 'Jalisco'),
    'san miguel el alto': ('San Miguel El Alto', 'Jalisco'),
    'tepatitlán': ('Tepatitlán', 'Jalisco'),
    'zapopan periférico': ('Zapopan Periférico', 'Jalisco'),
    'zapotlanejo': ('Zapotlanejo', 'Jalisco'),
    'la piedad': ('La Piedad', 'Michoacán'),
    'lázaro cárdenas': ('Lázaro Cárdenas', 'Michoacán'),
    'morelia': ('Morelia', 'Michoacán'),
    'morelia tarimbaro': ('Morelia Tarimbaro', 'Michoacán'),
    'sahuayo': ('Sahuayo', 'Michoacán'),
    'uruapan': ('Uruapan', 'Michoacán'),
    'zamora': ('Zamora', 'Michoacán'),
    'cuernavaca': ('Cuernavaca', 'Morelos'),
    'tepic': ('Tepic', 'Nayarit'),
    'apodaca': ('Apodaca', 'Nuevo León'),
    'escobedo': ('Escobedo', 'Nuevo León'),
    'guadalupe': ('Guadalupe', 'Nuevo León'),
    'lincoln 2': ('Lincoln 2', 'Nuevo León'),
    'monterrey estadio': ('Monterrey Estadio', 'Nuevo León'),
    'monterrey universidad': ('Monterrey Universidad', 'Nuevo León'),
    'santa catarina paseo': ('Santa Catarina Paseo', 'Nuevo León'),
    'santa catarina cedis': ('Santa Catarina Cedis', 'Nuevo León'),
    'mazatlán': ('Mazatlán', 'Sinaloa'),
    'oaxaca': ('Oaxaca', 'Oaxaca'),
    'puebla av.31': ('Puebla Av.31', 'Puebla'),
    'puebla estadio': ('Puebla Estadio', 'Puebla'),
    'corregidora': ('Corregidora', 'Querétaro'),
    'el marquez': ('El Marquez', 'Querétaro'),
    'querétaro': ('Querétaro', 'Querétaro'),
    'san juan del río': ('San Juan Del Río', 'Querétaro'),
    'cancún': ('Cancún', 'Quintana Roo'),
    'san luis potosí': ('San Luis Potosí', 'San Luis Potosí'),
    'soledad de graciano': ('Soledad De Graciano', 'San Luis Potosí'),
    'culiacán': ('Culiacán', 'Sinaloa'),
    'culiacán pedro infante': ('Culiacán Pedro Infante', 'Sinaloa'),
    'los mochis': ('Los Mochis', 'Sinaloa'),
    'hermosillo cedis': ('Hermosillo Cedis', 'Sonora'),
    'nogales': ('Nogales', 'Sonora'),
    'cd obregón': ('Cd Obregón', 'Sonora'),
    'tlaxcala': ('Tlaxcala', 'Tlaxcala'),
    'villahermosa': ('Villahermosa', 'Tabasco'),
    'nuevo laredo': ('Nuevo Laredo', 'Tamaulipas'),
    'reynosa': ('Reynosa', 'Tamaulipas'),
    'tampico': ('Tampico', 'Tamaulipas'),
    'coatzacoalcos': ('Coatzacoalcos', 'Veracruz'),
    'veracruz': ('Veracruz', 'Veracruz'),
    'xalapa': ('Xalapa', 'Veracruz'),
    'mérida': ('Mérida', 'Yucatán'),
    'ticul': ('Ticul', 'Yucatán'),
    'zacatecas': ('Zacatecas', 'Zacatecas'),
}
